name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: yarn
    - run: yarn cypress:run run
      continue-on-error: true
    - uses: mainmatter/continue-on-error-comment@v1
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: cypress/cypress-logs